name: telegram notify on push to test
on:
  push:
    branches:
      - main
      - test
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            //----------------------------//
            
            ${{ github.actor }} pushed to `test branch`
            
            *Repository* : ${{ github.repository }}
            
            *Commit message* : ${{ github.event.head_commit.message }}
            
            [See changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            
            //----------------------------//